#!/bin/bash
if [ "$MAV_USER" = "" ]
then
    echo -n "mav username: "
    read MAV_USER
fi

if [ "$MAV_PASS" = "" ]
then
    echo -n "password: "
    read -s MAV_PASS
fi

if apt-cache policy cifs-utils | grep -q "Installed: (none)"
then
    echo "installing missing cifs tools..."
    sudo apt install -y cifs-utils
fi

if ! timeout 4 ping -c 1 homefs.coloradomesa.edu >/dev/null
then
  echo "cannot access Colorado Mesa share folders."
  exit 1
fi


for locmnt in \
    $HOME/cmu/f://homefs.coloradomesa.edu/Home/$MAV_USER \
    $HOME/cmu/k://homefs.coloradomesa.edu/courses \
    $HOME/cmu/r://sharefs.coloradomesa.edu/share \
    $HOME/cmu/s://sharefs.coloradomesa.edu/share3 \
    #eol
do
  loc=${locmnt%%:*}
  mnt=${locmnt#*:}
  host=${mnt#//}
  host=${host%%/*}
  sudo umount $loc 2>/dev/null
  sudo mkdir -p $loc
  sudo mount -t cifs -o username="$MAV_USER",password="$MAV_PASS",uid="$(id -u)",gid="$(id -g)",forceuid,forcegid $mnt $loc
done
